server:
  port: 8080
# Binding health checks to a different port
management:
  port: 8081

# disable all management enpoints except health
endpoints:
  enabled: false
  health:
    enabled: true

spring:
  # Spring JDBC configuration
  datasource:
    # Let Spring Boot auto-configure an embedded HSQL database
    url:
  jpa:
#    properties:
#      hibernate:
#        show_sql: true
#        format_sql: true
    hibernate:
      ddl-auto: none
logging:
  level:
    org:
      hibernate:
        type: trace

# The application configuration properties
quickstart:
  generateOrderPeriod: 2s
  processOrderPeriod: 5s
